import type { Metadata } from 'next';
import './globals.scss';
import RootLayoutClient from '@/shared/components/root-layout/root-layout.component';

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'booking-system',
  description: 'Generated by create next app',
  // icons: {
  //   icon: '/favicon.ico',
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RootLayoutClient>{children}</RootLayoutClient>
      </body>
    </html>
  );
}
