#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running linters..."

echo "Running linters on backend..."
npm run lint-backend

if [ $? -ne 0 ]; then
  echo "Backend linting failed!"
  exit 1
fi

echo "Running linters on frontend..."
npm run lint-frontend

if [ $? -ne 0 ]; then
  echo "Frontend linting failed!"
  exit 1
fi

